// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/call/call.proto

package go_micro_srv_go

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Call service

type CallService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Call_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Call_PingPongService, error)
}

type callService struct {
	c    client.Client
	name string
}

func NewCallService(name string, c client.Client) CallService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.go"
	}
	return &callService{
		c:    c,
		name: name,
	}
}

func (c *callService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Call.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Call_StreamService, error) {
	req := c.c.NewRequest(c.name, "Call.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &callServiceStream{stream}, nil
}

type Call_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type callServiceStream struct {
	stream client.Stream
}

func (x *callServiceStream) Close() error {
	return x.stream.Close()
}

func (x *callServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *callServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *callServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *callService) PingPong(ctx context.Context, opts ...client.CallOption) (Call_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Call.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &callServicePingPong{stream}, nil
}

type Call_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type callServicePingPong struct {
	stream client.Stream
}

func (x *callServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *callServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *callServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *callServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *callServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Call service

type CallHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Call_StreamStream) error
	PingPong(context.Context, Call_PingPongStream) error
}

func RegisterCallHandler(s server.Server, hdlr CallHandler, opts ...server.HandlerOption) error {
	type call interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Call struct {
		call
	}
	h := &callHandler{hdlr}
	return s.Handle(s.NewHandler(&Call{h}, opts...))
}

type callHandler struct {
	CallHandler
}

func (h *callHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.CallHandler.Call(ctx, in, out)
}

func (h *callHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CallHandler.Stream(ctx, m, &callStreamStream{stream})
}

type Call_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type callStreamStream struct {
	stream server.Stream
}

func (x *callStreamStream) Close() error {
	return x.stream.Close()
}

func (x *callStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *callStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *callStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *callHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.CallHandler.PingPong(ctx, &callPingPongStream{stream})
}

type Call_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type callPingPongStream struct {
	stream server.Stream
}

func (x *callPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *callPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *callPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *callPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *callPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
